# Learning Tool: 
# Workbook Module:

# Intro
 With the advances in technology we got overwhelmed suddenly overwhelmed by a lot of information everyday.
 Our personal mail, work mail, student mail, whatsapp, student blackboard, software documentation of at least 3 programming languages opened at the sametime, stackoverflow 200 tabs 
 
 looking for a bug solution in your code, Ebooks, Pdfs, IDEs, Slack groups of different projects, plus the temptation to open youtube or 9gag. 
 Everything interrupting at the same time and distracting us from our main activity, don't allowing us to focus
 and to properly manage information. As human beings is know that we are not good to multitask (Text and Drive for example) so that
 is why Workbook is being developed.
 
 The aim of this project is to have a desktop well organized knowledge base of almost everything but specially for programming
 language learning and refreshing knowledge. The idea is simple: 
 
 Learn->Practice->Code at the same time, but instead of having 1 IDE, 1 Pdf, 2 tabs, 1 doc file opened at the same time
 in the browser that has already 100 tabs, or 3 browsers opened at the same time and forget 3 years later where I had those 
 examples of a WSDL that I need to leave the office early today or that I need to refresh my knowledge in a product presentation and avoid the uncomfortable "Let me, hmmm, member..." yeah
 that presentation of 5 years ago, let's check this folder. You follow my example... 



+----------------------------------------------------+
|                                                    |
|  +--------------+ +-------------+ +-------------+  |
|  |              | |             | |             |  |
|  |Question      | |  Learn      | | Code        |  |
|  |Module        | |  Module     | | Runner      |  | 
|  |              | |             | |             |  |   
|  |              | |             | |             |  |
|  |              | |             | |             |  |
|  +--------------+ +-------------+ +-------------+  |
|                   Workbook Module                  |
+----------------------------------------------------+



1)Updates
---------

### Update 30/03/2017

-Release as minimum viable product.

2)Project Requirements
----------------------
-Question Module []
-Lean Module(Not Yet Developed)
-Code Runner (Not yet Developed)

3)Architecture
--------------
MVC

4)Work Methodology
------------------- 
"Just program the modules"

5)Copyright Information
----------------------- 
Code is under [https://www.apache.org/licenses/LICENSE-2.0.txt]
